project_id = "gnhbkevtoajzdpsengki"

[functions.reset-password]
verify_jwt = false

[functions.exercise-gif]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.notify-announcement]
verify_jwt = false

[functions.notify-friends]
verify_jwt = false

[functions.notify-suggestion]
verify_jwt = false

[functions.workout-ai]
verify_jwt = false

[functions.notify-friend-request]
verify_jwt = false

[functions.notify-comment]
verify_jwt = false

[functions.test-push]
verify_jwt = false

[functions.search-exercisedb]
verify_jwt = false