// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my Grim profile",
  description: "Get the signed-in user's Grim profile: nickname, title, weight, height, experience level and training days per week.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "nickname, display_title, weight_kg, height_cm, age, gender, experience_level, training_days_per_week, plan_start_date, is_honorary"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-workouts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";
var list_recent_workouts_default = defineTool2({
  name: "list_recent_workouts",
  title: "List recent workouts",
  description: "List the signed-in user's most recently completed Grim workouts, including week, day, distance, pace and pulse.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many workouts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workout_completions").select("week, day, done, skipped, logged_distance_km, logged_tempo, logged_pulse, user_comment, updated_at").eq("user_id", ctx.getUserId()).eq("done", true).order("updated_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? JSON.stringify(rows, null, 2) : "No completed workouts found."
        }
      ],
      structuredContent: { workouts: rows }
    };
  }
});

// src/lib/mcp/tools/get-week-plan.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_week_plan_default = defineTool3({
  name: "get_week_plan",
  title: "Get training plan for a week",
  description: "Get the signed-in user's planned Grim sessions for a given week number, with session names and exercise details.",
  inputSchema: {
    week: z2.number().int().min(1).max(104).describe("Week number in the training plan.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ week }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workout_plans").select("week, day, session_name, details, tempo, is_circuit").eq("user_id", ctx.getUserId()).eq("week", week).order("day", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? JSON.stringify(rows, null, 2) : `No plan found for week ${week}.`
        }
      ],
      structuredContent: { week, sessions: rows }
    };
  }
});

// src/lib/mcp/tools/complete-workout.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var complete_workout_default = defineTool4({
  name: "complete_workout",
  title: "Mark a workout as completed",
  description: "Mark a Grim session for a given week and day as completed for the signed-in user, optionally with distance, pace, pulse and a comment.",
  inputSchema: {
    week: z3.number().int().min(1).max(104).describe("Week number in the training plan."),
    day: z3.string().trim().min(1).describe("Day identifier used in the plan, e.g. 'M\xE5ndag'."),
    distance_km: z3.number().min(0).max(1e3).optional().describe("Logged distance in kilometres."),
    tempo: z3.string().trim().optional().describe("Logged pace, e.g. '5:30'."),
    pulse: z3.number().int().min(20).max(250).optional().describe("Average pulse in bpm."),
    comment: z3.string().trim().max(500).optional().describe("Short note about the session.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ week, day, distance_km, tempo, pulse, comment }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workout_completions").upsert(
      {
        user_id: ctx.getUserId(),
        week,
        day,
        done: true,
        skipped: false,
        logged_distance_km: distance_km ?? null,
        logged_tempo: tempo ?? null,
        logged_pulse: pulse ?? null,
        user_comment: comment ?? null,
        updated_at: (/* @__PURE__ */ new Date()).toISOString()
      },
      { onConflict: "user_id,week,day" }
    ).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Marked week ${week}, ${day} as completed.` }],
      structuredContent: { completion: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gnhbkevtoajzdpsengki";
var mcp_default = defineMcp({
  name: "grim",
  title: "Grim",
  version: "0.1.0",
  instructions: "Tools for the Grim training app. Read the signed-in user's profile, their planned sessions for a week, their recently completed workouts, and mark a session as completed.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_week_plan_default, list_recent_workouts_default, complete_workout_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
